services:
  rabbit:
    image: rabbitmq:3-management-alpine
    volumes:
        - rabbit_volume:/var/lib/rabbitmq/
    expose:
        - "5672"
        - "15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  db:
    image: postgres:16.3-alpine3.20
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
    expose:
      - "5432"

  notifications-admin:
    build:
      context: ../notifications_admin/
      dockerfile: Dockerfile
    image: notifications-admin
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    working_dir: /app
    command: >
      sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"


volumes:
  db_volume:
  rabbit_volume: 