services:
  rabbit:
    image: rabbitmq:3-management
    volumes:
        - rabbit_volume:/var/lib/rabbitmq/
    ports:
        - "5672:5672"
        - "15672:15672"
    env_file:
      - ./.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  db:
    image: postgres:16.3
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

volumes:
  db_volume:
  rabbit_volume: 