services:
  rabbit:
    image: rabbitmq:3-management
    volumes:
        - rabbit_volume:/var/lib/rabbitmq/
    ports:
        - "5672:5672"
        - "15672:15672"
    env_file:
      - ./.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  db:
    image: postgres:16.3
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  fake-auth-service:
    build:
      context: ../fake_auth_service/
      dockerfile: Dockerfile
    image: fake-auth-service
    expose:
      - "8090"
    ports:
      - "8090"
    working_dir: /app
    command: >
      sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"

  notification_processor:
    build:
      context: ../notification_processor/
      dockerfile: Dockerfile
    image: notification_processor
    working_dir: /app
    command: >
      sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"

  notifications-admin:
    build:
      context: ../notifications_admin/
      dockerfile: Dockerfile
    image: notifications-admin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"

  notifications-api:
    build:
      context: ../notifications_api/
      dockerfile: Dockerfile
    image: notifications-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    working_dir: /app
    command: >
      sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"

  notifications-worker:
    build:
      context: ../notifications_worker/
      dockerfile: Dockerfile
    image: notifications-worker
    env_file:
      - ./.env
    depends_on:
      rabbit:
        condition: service_healthy

volumes:
  db_volume:
  rabbit_volume: 